package com.blueradix.android.jetpacknavigation.ui.main;

import androidx.lifecycle.ViewModelProvider;

import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.navigation.NavController;
import androidx.navigation.NavDirections;
import androidx.navigation.Navigation;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.blueradix.android.jetpacknavigation.R;
import com.blueradix.android.jetpacknavigation.databinding.MainFragmentBinding;

public class MainFragment extends Fragment {

    private MainViewModel mViewModel;
    private MainFragmentBinding binding;

    public static MainFragment newInstance() {
        return new MainFragment();
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        binding = MainFragmentBinding.inflate(inflater, container, false);
        View view = binding.getRoot();
        return view;
    }

//    @Override
//    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
//        super.onActivityCreated(savedInstanceState);
//        mViewModel = new ViewModelProvider(this).get(MainViewModel.class);
//        // TODO: Use the ViewModel
//    }


    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mViewModel = new ViewModelProvider(this).get(MainViewModel.class);

        binding.navigateToSecondButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //locate the NavController associated with this view
                NavController navController = Navigation.findNavController(view);
                //perform the navigation
                navController.navigate(R.id.mainToSecondAction);
            }
        });

        binding.navigateToThirdButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //First we get the text input in the editTextName widget
                String usersName = binding.editTextName.getText().toString();

                //first get the action from the autogenerated class MainFragmentDirections
                MainFragmentDirections.MainToThirdAction action = MainFragmentDirections.mainToThirdAction();
                //set the value to pass into the action.
                action.setName(usersName);
                //perform the navigation
                NavController navController = Navigation.findNavController(view);
                navController.navigate(action);
            }
        });
    }
}